export const ALGORITHM_VERSIONS = Object.freeze({
  itemVersion: 'navigator-item-v1',
  adaptiveAssessment: 'navigator-adaptive-v2',
  assessmentBlueprintEligibility: 'navigator-assessment-bank-eligibility-v1',
  assessmentReconciliation: 'navigator-reconciliation-v1',
  learnerEvidenceAdapter: 'praxis-learner-evidence-v1',
  assessmentHandoff: 'praxis-assessment-handoff-v1',
  irtPosterior: 'praxis-irt-2pl-grid-eap-v1',
  irtStoppingPolicy: 'praxis-irt-uncertainty-stop-v1',
  assessmentItemDrafting: 'praxis-ai-item-draft-validator-v1',
  laborMarketBiasCorrection: 'praxis-labor-poststratification-v1',
  taskNetworkCrosswalk: 'praxis-task-network-crosswalk-v1',
  graphSequentialExperiment: 'praxis-graph-sequential-offline-eval-v1',
  outcomePriorEstimator: 'praxis-outcome-prior-v1',
  escoTargetProfile: 'praxis-esco-target-profile-v3',
  iscoSeniorityDerivation: 'praxis-isco-major-group-v1',
  romeTransitionCrossDomain: 'praxis-rome-transition-cross-domain-v1',
  escoRomeOccupationMatch: 'praxis-esco-rome-occupation-match-v1',
  adaptiveDiagnosticSelection: 'praxis-adaptive-diagnostic-infogain-v3',
  seniorityDirectionGuard: 'praxis-seniority-direction-guard-v1',
  cvParserRules: 'navigator-cv-parser-rules-v0.1',
  escoSkillLinker: 'praxis-esco-retrieve-rank-v1',
  learnerSkillConfirmation: 'praxis-learner-skill-confirmation-v1',
  masteryRubric: 'praxis-mastery-rubric-v1',
  learnerContextCapture: 'praxis-learner-context-v3',
  learnerContextSurvey: 'praxis-context-survey-v3',
  agentGateway: 'praxis-agent-gateway-v1',
  developmentPlan: 'praxis-development-plan-v1',
  careerReport: 'praxis-career-report-v1',
  careerAgent: 'praxis-career-agent-v1',
  directionRecommendations: 'praxis-direction-recommendations-v2',
  cvExperienceInference: 'praxis-cv-experience-inference-v1',
  profileTargeting: 'navigator-profile-targeting-v0.1',
  recommendationWeights: 'navigator-recommendation-weights-v1',
  recommendationRanker: 'praxis-rank-reliable-v4',
  priorityFormula: 'navigator-priority-v1',
  pathwayBuilder: 'navigator-pathway-builder-v0.1',
  reportTemplate: 'navigator-report-template-v0.1',
});

export type RegisteredAlgorithm = keyof typeof ALGORITHM_VERSIONS;
